name: Teste básico do site

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validar-site:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Verificar se arquivos existem
        run: |
          echo "Verificando arquivos..."
          ls -lah
          test -f index.html && echo "index.html encontrado!"
